---
title: EWT SNPs common to other groups
output:
  html_document:
    df_print: paged
    code_folding: hide
knit: (function(input, ...) {
    rmarkdown::render(
      input,
      output_dir = "html_output"
    )
  })
---


#  {.tabset .tabset-fade .tabset-pills}

## Intro

### Libraries
```{r warning=FALSE, message=FALSE, class.source = 'fold-show'}
library(httpgd)
library(VariantAnnotation)
library(DT)
```

### Loading the data
```{r warning=FALSE, message=FALSE, class.source = 'fold-show'}
resultToSave <- file.path("data", "unique_SNPs_vs_all.Rds")
groupUniqueSnps <- readRDS(resultToSave)
groupUniqueSnps <- groupUniqueSnps[-grep("S_Group", names(groupUniqueSnps))]
```

## Results

### Which groups have SNPs common to the EWT groups
```{r}
ewts.id <- grep("EWT", names(groupUniqueSnps))

dt1 <- t(sapply(groupUniqueSnps[-ewts.id], function(currGroup) {
  sapply(groupUniqueSnps[ewts.id], function(currEWT) {
    any(rowRanges(currGroup) %in% rowRanges(currEWT))
  })
}))

datatable(dt1) %>%
  formatStyle(
    colnames(dt1),
    fontWeight = styleEqual(c(FALSE, TRUE), c("normal", "bold")),
    color = styleEqual(c(FALSE, TRUE), c("black", "red")),
  )
```


### How many SNPs are common?

```{r warning=FALSE, message=FALSE}
dt2 <- t(sapply(groupUniqueSnps[-ewts.id], function(currGroup) {
  sapply(groupUniqueSnps[ewts.id], function(currEWT) {
    sum(rowRanges(currGroup) %in% rowRanges(currEWT))
  })
}))

datatable(dt2) %>%
  formatStyle(
    colnames(dt2),
    fontWeight = styleInterval(0, c("normal", "bold")),
    color = styleInterval(0, c("black", "red")),
  )
```

### What fraction is common?

```{r}
dt2 <- t(sapply(groupUniqueSnps[-ewts.id], function(currGroup) {
  sapply(groupUniqueSnps[ewts.id], function(currEWT) {
    frac <- sum(rowRanges(currGroup) %in% rowRanges(currEWT)) / length(rowRanges(currGroup))
  })
}))

datatable(dt2) %>%
  formatPercentage(colnames(dt2), 1) %>%
  formatStyle(
    colnames(dt2),
    fontWeight = styleInterval(0, c("normal", "bold")),
    color = styleInterval(0, c("black", "red")),
  )
```

## sessionInfo
```{r}
sessionInfo()
```
